name: Deploy GCP Cloud Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy GCP Cloud Run
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment}}
    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ vars.APP_NAME }}:${{ github.ref_name }}
      LOCATION: europe-west1
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_CICD_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}/providers/github
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Configure Docker
        run: gcloud auth configure-docker eu.gcr.io --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: >
          gcloud run deploy ${{ vars.APP_NAME }}
          --image $IMAGE_NAME
          --region $LOCATION
          --min-instances=0
          --max-instances=1
          --platform managed
          --cpu=1
          --memory=128Mi
          --port=80
          --revision-suffix=${{ github.ref_name }}
