name: GCP Deploy Dev/Prod

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Upload Docker image
    uses: ./.github/workflows/upload-service.yml
    with:
      tag: ${{ env.github.sha }}
  deploy-dev:
    name: Dev Deploy
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: dev
    needs: upload
