name: GCP Deploy Dev/Prod

on:
  push:
    tags: [v*.*.*]

jobs:
  deploy-prod:
    name: Prod Deploy
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: prod
  deploy-dev:
    name: Dev Deploy
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: dev
