name: Build and Upload Docker image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to deploy
        required: true
        type: string
      APP_NAME:
        description: The name of the app
        required: true
        type: string
    secrets:
      GCP_PROJECT_CICD_ID:
        description: The GCP project ID
        required: true
      GCP_PROJECT_CICD_NUMBER:
        description: The GCP project number
        required: true
      GCP_SERVICE_ACCOUNT:
        description: The GCP service account
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        description: The GCP workload identity provider
        required: true

  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
    secrets:
      GCP_PROJECT_CICD_ID:
        required: true
      GCP_PROJECT_CICD_NUMBER:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build:
    name: Build and Upload Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_CICD_ID }}/${{ inputs.APP_NAME }}/${{ inputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_CICD_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}/providers/github
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Configure Docker
        run: gcloud auth configure-docker eu.gcr.io --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME
